services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=<your_user_name>'
      - 'POSTGRES_DB=<your_db_nzme>'
      - 'POSTGRES_PASSWORD=<your_password>'
    volumes:
      - './volumes/ivbooking/postgres:/var/lib/postgresql/data'